[package]
name = "geosuggest-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.18"

anyhow = "1.0"
wasm-bindgen = "0.2.69"

log = "0.4.6"
wasm-logger = "0.2.0"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_qs = "0.8"
