[workspace]
resolver = "2"
members = [
  "geosuggest",
  "geosuggest-*",
]

[workspace.package]
version = "0.8.5"
authors = ["geosuggest contributors"]
license = "MIT"

[workspace.dependencies]
anyhow = "1"
test-log = { version = "0.2", default-features = false, features = ["trace"] }
tracing = "0.1"
tracing-subscriber = {
  version = "0.3",
  features = [
    "env-filter",
    "fmt",
  ]
}

config = "0.15"
csv = "1"
geoip2 = "0.1"
kiddo = {
  version = "6.0",
  default-features = false,
  features = [
    "fixed",
    "rkyv_08",
  ]
}
rayon = "1"
# core
serde = { version = "1", features = ["derive"] }
serde_json = "1"
strsim = "0.11"

itertools = "0.15"
rkyv = { version = "0.8" }

ntex = { version = "3.7", features = ["tokio"] }
ntex-cors = "3"
ntex-files = "3"
# service
oaph = { version = "0.2" }

clap = { version = "4.5", features = ["derive"] }
futures = "0.3"
reqwest = {
  version = "0.13",
  default-features = false,
  features = [
    "rustls",
  ]
}
tokio = {
  version = "1",
  features = [
    "macros",
    "net",
    "rt-multi-thread",
  ]
}
# utils
zip = "8"
