[package]
name = "geosuggest-core"
version = "0.1.1"
edition = "2021"

[features]
default = []
oaph_support = ["oaph"]
geoip2_support = ["geoip2"]

[dependencies]
log = "0.4"
csv = "1.1"
serde = {version = "1.0", features = ["derive"] }
rayon = "1.5"
strsim = "0.10"
kdtree = "0.6"

geoip2 = { version = "0.1.3", optional = true }
oaph = {version = "0.1", optional = true }

serde_json = "1.0"

[dev-dependencies]
env_logger = "0.8"
procinfo = "0.4"
