[package]
name = "geosuggest-core"
version = "0.1.0"
edition = "2018"

[features]
default = []
oaph_support = ["oaph"]

[dependencies]
log = "0.4"
csv = "1.1"
serde = {version = "1.0", features = ["derive"] }
rayon = "1.5"
strsim = "0.10"
kdtree = "0.6"
oaph = {version = "0.1", optional = true }
serde_json = "1.0"

[dev-dependencies]
env_logger = "0.8"
