[package]
name = "geosuggest"
version = "0.1.2"
edition = "2021"

default-run = "geosuggest"

[[bin]]
name = "geosuggest"
path = "src/main.rs"

[features]
geoip2_support = ["geosuggest-core/geoip2_support"]

[dependencies]
log = "0.4"
env_logger = "0.8"
serde = { version = "1.0", features = ["derive"] }

ntex = { version = "0.5.10", features = ["tokio"] }
ntex-files = "0.1"
ntex-cors = "0.2"
config = "0.11"
geosuggest-core = { path = "../geosuggest-core", features = ["oaph_support"] }

# openapi3
oaph = "0.1"

[dev-dependencies]
serde_json = "1.0"
