[package]
name = "geosuggest"
version = "0.2.5"
edition = "2021"

default-run = "geosuggest"

[[bin]]
name = "geosuggest"
path = "src/main.rs"

[features]
default = ["tokio", "geoip2_support"]
geoip2_support = ["geosuggest-core/geoip2_support"]
glommio = ["ntex/glommio"]
tokio = ["ntex/tokio"]

[dependencies]
log = "0.4"
env_logger = "0.8"
serde = { version = "1", features = ["derive"] }

ntex = { version = "0.6.3" }
ntex-files = "0.2"
ntex-cors = "0.3"
config = "0.12"
geosuggest-core = { path = "../geosuggest-core", features = ["oaph_support"] }

# openapi3
oaph = "0.1"

[dev-dependencies]
serde_json = "1"
