[package]
name = "geosuggest"
version = "0.2.6"
edition = "2021"

default-run = "geosuggest"

[[bin]]
name = "geosuggest"
path = "src/main.rs"

[features]
default = ["tokio", "geoip2_support"]
geoip2_support = ["geosuggest-core/geoip2_support"]
glommio = ["ntex/glommio"]
tokio = ["ntex/tokio"]

[dependencies]
tracing.workspace = true
tracing-subscriber.workspace = true
serde.workspace = true
ntex.workspace = true
ntex-files.workspace = true
ntex-cors.workspace = true
config.workspace = true

geosuggest-core = { path = "../geosuggest-core", features = ["oaph_support"] }

# openapi3
oaph.workspace = true 

[dev-dependencies]
serde_json = "1"
test-log.workspace = true