[package]
name = "geosuggest-utils"
version = "0.1.1"
edition = "2021"


[[bin]]
name = "geosuggest-build-index"
path = "src/build-index.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing.workspace = true
tracing-subscriber.workspace = true

geosuggest-core = { path = "../geosuggest-core" }

getopts = "0.2"
