openapi: 3.0.0
info:
  title: geosuggest
  version: {{version}}
servers:
  - url: {{url_path_prefix}}
paths:
  /api/city/get:
    get:
      tags:
      - get
      description: retrieve city by geonameid
      parameters:
        {{GetCityQuery}}
      responses:
        '200':
          content:
            application/json:
              schema:
                {{GetCityResult}}
  /api/city/capital:
    get:
      tags:
      - capital
      description: retrieve country capital 
      parameters:
        {{GetCapitalQuery}}
      responses:
        '200':
          content:
            application/json:
              schema:
                {{GetCapitalResult}}
  /api/city/suggest:
    get:
      tags:
      - suggest
      description: suggest city by text input
      parameters:
        {{SuggestQuery}}
      responses:
        '200':
          content:
            application/json:
              schema:
                {{SuggestResult}}
  /api/city/reverse:
    get:
      tags:
      - reverse
      description: find city by coordinates
      parameters:
        {{ReverseQuery}}
      responses:
        '200':
          content:
            application/json:
              schema:
                {{ReverseResult}}
  /api/city/geoip2:
    get:
      tags:
      - geoip2
      description: find city by IP address
      parameters:
        {{GeoIP2Query}}
      responses:
        '200':
          content:
            application/json:
              schema:
                {{GeoIP2Result}}
definitions:
  {{oaph::definitions}}
