openapi: 3.0.0
info:
  title: geosuggest 
  version: 0.1.0
paths:
  /api/city/suggest:
    get:
      tags:
      - suggest
      description: suggest city by text input
      parameters:
        {{SuggestQuery}}
      responses:
        '200':
          content:
            application/json:
              schema:
                {{SuggestResult}}
  /api/city/reverse:
    get:
      tags:
      - reverse
      description: find city by coordinates 
      parameters:
        {{ReverseQuery}}
      responses:
        '200':
          content:
            application/json:
              schema:
                {{ReverseResult}}
  /api/city/geoip2:
    get:
      tags:
      - geoip2
      description: find city by IP address 
      parameters:
        {{GeoIP2Query}}
      responses:
        '200':
          content:
            application/json:
              schema:
                {{GeoIP2Result}}
definitions:
  {{oaph::definitions}}
