name: tests suite

on: [push, pull_request]

jobs:
  test:
    # to prevent double run on push and pull_request
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    name: clippy&test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: clippy
      - run: cargo clippy --workspace --no-default-features --features="tokio,geoip2,tracing"
      - run: cargo test --workspace --no-default-features --features="tokio,geoip2,tracing"
      - run: cargo run -p geosuggest-examples --release --bin simple
